import { protectedRouter } from "../../middleware/protected";
import { management } from "./management";
import { clinical } from "./clinical";
import { billing } from "./billing";
import { care } from "./care";
import { fulfillment } from "./fulfillment";
import { operations } from "./operations";
import { laboratory } from "./laboratory";
import { administration } from "./administration";
import { communication } from "./communication";
import { receptionist } from "./receptionist";

export const hospitalRoutes = protectedRouter();
receptionist(hospitalRoutes);
management(hospitalRoutes);
clinical(hospitalRoutes);
billing(hospitalRoutes);
care(hospitalRoutes);
fulfillment(hospitalRoutes);
operations(hospitalRoutes);
laboratory(hospitalRoutes);
administration(hospitalRoutes);
communication(hospitalRoutes);
